### ISSUE TITLE
Make tree-sitter-yuck opensource?

### ISSUE THREAD

**Issue by winston0410** [dylanHanger/dotfiles#1]
Hi I have done a search like this, and I found your repo. Do you mind pushing your `tree-sitter-yuck` code to a repository, so that I can help out and enjoy that treesitter highlight as well?:). Hopefully you won't feel offended for this message here.

https://github.com/search?q=tree-sitter-yuck&type=code

**Comment by dylanHanger** [comment]
I would be more than happy to open-source this, but it was mostly a couple hours of playing around to see how treesitter worked. I never intended it to be anything more than a little bit of fun, and unfortunately university work took priority. That means its little more than a shell made by someone with _no idea_ what they were doing.

That being said, [here it is](https://github.com/dylanHanger/tree-sitter-yuck).

**Comment by winston0410** [comment]
Sure thing. I am no so familiar with tree-sitter as well, but I have done one previously with `hjson`. Hopefully I can help out with this.
